In [3]:
import numpy as np

# Init

In [4]:
def casting(my_list):
    return np.array(my_list)

In [5]:
casting([1, 2, 3])

array([1, 2, 3])

In [6]:
casting([
    [1, 2, 3],
    [4, 5, 6],
    [2, 3, 4]
])

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4]])

In [7]:
np.arange(1, 11, 2) 

array([1, 3, 5, 7, 9])

In [8]:
np.zeros((5,1)).size

5

In [9]:
np.zeros(5).size

5

In [10]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# return evenly spaced number overall specified interval
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [13]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
# random over uniform distribution [0,1]
np.random.rand(10)

array([0.9109911 , 0.30481495, 0.48691188, 0.52998349, 0.13208443,
       0.98647527, 0.65229052, 0.44841825, 0.98224578, 0.01493777])

In [15]:
np.random.rand(5,4)

array([[0.39663242, 0.22058937, 0.01724371, 0.04247326],
       [0.03098072, 0.6195314 , 0.32183707, 0.32790539],
       [0.14932052, 0.16117228, 0.80862267, 0.0296666 ],
       [0.22223621, 0.16737924, 0.83408802, 0.06646383],
       [0.47421907, 0.24063013, 0.28572676, 0.07018154]])

In [16]:
# random from standard normal distribution
np.random.randn(5)

array([-1.28588166,  1.2887916 ,  0.62417585,  0.5278017 , -0.2799717 ])

In [17]:
np.random.randn(3,1)

array([[0.00556375],
       [1.25416989],
       [0.41191707]])

In [18]:
# simple random integer
np.random.randint(1, 200, (3,3))

array([[ 51,  12,  34],
       [110, 188, 108],
       [ 74, 125, 105]])

# Reshaping

In [19]:
a = np.arange(25)
b = np.random.randint(0, 50, 10)

In [20]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[11 27 11 21  3 17 28 15 30 34]


In [21]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
a.reshape(25,1).shape

(25, 1)

In [23]:
a.shape

(25,)

In [24]:
a.dtype

dtype('int64')

In [25]:
b.max()

34

In [26]:
b.argmax()

9

# operations / broadcasting

In [27]:
a = np.arange(0, 10)
print(a)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [28]:
a + a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
a.reshape(1, 10) + a.reshape(1, 10)

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [30]:
a * a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [31]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
a / a

/home/klagrange/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [33]:
a ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [34]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [35]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [36]:
np.max(a)

9

In [37]:
a.max()

9

In [38]:
b = np.zeros((2,2))
c = np.array([[10, 100]])

print("b = {0} | shape = {1}".format(b, b.shape))
print("c = {0} | shape = {1}".format(c, c.shape))

b = [[0. 0.]
 [0. 0.]] | shape = (2, 2)
c = [[ 10 100]] | shape = (1, 2)


In [39]:
b + c

array([[ 10., 100.],
       [ 10., 100.]])

# indexing

In [55]:
a = np.arange(0, 10)
a_copy = a.copy() 
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
a[9]

9

In [57]:
a[0:5]

array([0, 1, 2, 3, 4])

In [58]:
a[0:5] = -100 # mutates in-place

In [59]:
a

array([-100, -100, -100, -100, -100,    5,    6,    7,    8,    9])

In [60]:
a[:] = 100 # mutates in-place

In [61]:
a

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [79]:
a_slice = a[0:6] # pointer the first of array a

In [83]:
id(a_slice) == id(a[0:6])

False

In [63]:
a_slice[:] = 33

In [86]:
a[0:6].__repr__() == a_slice.__repr__()

True

In [87]:
print(id(a), a)

140247133540640 [ 33  33  33  33  33  33 100 100 100 100]


In [88]:
print(id(a_copy), a_copy)

140247133541600 [0 1 2 3 4 5 6 7 8 9]


In [76]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [77]:
mat[0][2] == mat[0,2]

True

In [90]:
mat[:2,1:]

array([[2, 3],
       [5, 6]])

# Conditional selection

In [114]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
bool_a = a > 4
bool_a

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [116]:
a[bool_a]

array([ 5,  6,  7,  8,  9, 10])

In [117]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
a[a > 4].__repr__() == a[bool_a].__repr__()

True